// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenguinSteamerSecondSeason;

namespace PenguinSteamerSecondSeason.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190609181234_CandleAndSoOn")]
    partial class CandleAndSoOn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PenguinSteamerSecondSeason.Models.Candle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Begin");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<decimal>("End");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal>("Max");

                    b.Property<decimal>("Min");

                    b.Property<string>("TimeStamp");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<decimal>("Volume");

                    b.HasKey("Id");

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("PenguinSteamerSecondSeason.Models.MBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("Currency1Id");

                    b.Property<int?>("Currency2Id");

                    b.Property<string>("DisplayName");

                    b.Property<int?>("ExchangeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("Currency1Id");

                    b.HasIndex("Currency2Id");

                    b.HasIndex("ExchangeId");

                    b.ToTable("MBoards");
                });

            modelBuilder.Entity("PenguinSteamerSecondSeason.Models.MCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MCurrency");
                });

            modelBuilder.Entity("PenguinSteamerSecondSeason.Models.MExchange", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DisplayName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("MExchanges");
                });

            modelBuilder.Entity("PenguinSteamerSecondSeason.Models.MTimeScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DisplayName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int>("SecondsValue");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("MTimeScales");
                });

            modelBuilder.Entity("PenguinSteamerSecondSeason.Models.MBoard", b =>
                {
                    b.HasOne("PenguinSteamerSecondSeason.Models.MCurrency", "Currency1")
                        .WithMany()
                        .HasForeignKey("Currency1Id");

                    b.HasOne("PenguinSteamerSecondSeason.Models.MCurrency", "Currency2")
                        .WithMany()
                        .HasForeignKey("Currency2Id");

                    b.HasOne("PenguinSteamerSecondSeason.Models.MExchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId");
                });
#pragma warning restore 612, 618
        }
    }
}
